name: CI/CD

on:
  push:
    branches: [ mise-en-place-actions ]
  pull_request:
    branches: [ mise-en-place-actions ]

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Installation des clés ssh
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Pull de déploiement
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git switch ${{ secrets.MAIN_BRANCH }} && git pull && npm install && exit"

    - name: cleanup
      run: rm -rf ~/.ssh
